{% set name = "cognite-sdk" %}
{% set version = "7.72.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cognite_sdk-{{ version }}.tar.gz
  sha256: b40a3fa4ea86feb7cf4841fcbca6546d8052a502be47e5317632a352dc2e4db0

build:
  noarch: python
  preserve_egg_dir: yes
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry >=1.6
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - requests >=2.27.0,<3.0.0
    - requests-oauthlib >=1.0.0,<2.0.0
    - msal >=1.31.0,<2.0.0
    - packaging >=20.0.0
    - protobuf >=4.0.0
    - pip >=20.0.0
    - typing_extensions >=4
    - python-tzdata >=2024.1
    - numpy >=1.25.0
    - pandas >=2.1.0
  run_constrained:
    - geopandas >=0.14.0
    - shapely >=1.7.0
    - PyYAML >=6.0.0,<7.0.0

test:
  imports:
    - cognite.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cognitedata/cognite-sdk-python
  summary: Cognite Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haakonvt
