{% set name = "cognite-sdk" %}
{% set version = "7.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cognite_sdk-{{ version }}.tar.gz
  sha256: 317533747cf61a8a3ed8d99041465acdf65c83453c227c305798f0bea9ea8c7f

build:
  noarch: python
  preserve_egg_dir: yes
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry >=1.6
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - requests >=2.0.0,<3.0.0
    - requests-oauthlib >=1.0.0,<2.0.0
    - msal >=1.0.0,<2.0.0
    - protobuf >=3.16.0
    - pip >=20.0.0
    - typing_extensions >=4
    - graphlib-backport >=1.0.0,<2.0.0
    - backports.zoneinfo >=0.2.1
    - python-tzdata >=2023.3
    - numpy >=1.20.0,<2.0.0
    - pandas >=1.4
  run_constrained:
    - geopandas >=0.10.0
    - shapely >=1.7.0
    - PyYAML >=6.0.0,<7.0.0

test:
  imports:
    - cognite.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cognitedata/cognite-sdk-python
  summary: Cognite Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - haakonvt
